### ISSUE TITLE
tmtpro flag only adds tag to lysines, not n-term.

### ISSUE THREAD

**Issue by ChrisMcGann** [wilhelm-lab/oktoberfest#123] opened 2023-09-11 20:39 UTC
Hello,
Using the tmtpro flag in a config file only adds the tag to lysine. Attaching config file and input .csv. Thanks!

[prosit_input_minimal.zip](https://github.com/wilhelm-lab/oktoberfest/files/12580150/prosit_input_minimal.zip)

**Comment by picciama** [comment] 2023-09-12 09:57
Thanks for pointing this out. I was able to reproduce this and know the reason for it. It will be fixed as part of the new API release.

**Comment by ChrisMcGann** [comment] 2023-09-12 16:58
Awesome, glad to hear it.

**Closed** 2023-10-03 15:03 UTC
Labels: bug
