### ISSUE TITLE
Missing ProteinID in the generated Spectral Lib and timsTOF questions

### ISSUE THREAD

**Issue by ZhaoYaniBruker** [wilhelm-lab/oktoberfest#238] opened 2024-07-08 08:11 UTC
Dear developers,

I have used Oktoberfest to generate a Spectral Library from a .fasta file, however, there is no proteinID information in this Lib. I have checked the settings few times, still didn't get how to select this option. Could you please give a little hint? Thanks very much for your time.

Best regards.

**Comment by picciama** [comment] 2024-07-08 09:46
This is indeed not yet published but already close to completion. I will try to release this asap (hopefully this week).

**Comment by ZhaoYaniBruker** [comment] 2024-07-08 11:12
Dear Picciama,

Thank you very much for your reply. I am looking forward to see the new release.

I have another little question: I used "models": {"intensity": "Prosit_2020_intensity_HCD", "irt": "Prosit_2019_irt"}, "prediction_server": "koina.wilhelmlab.org:443" to generate the Spectral library. I am not sure if the modifications were included in the Prosit models, I mean these generally used modifications like "Ac(N-term)", "Ox(M)", and "C(carbo...)". Or, I have to manually setup these by myself. 

Thanks again for your reply.

**Comment by picciama** [comment] 2024-07-08 12:28
The way Oktoberfest works is that it applies static carbamidomethylation to C and variable oxidation to M. These are the only modifications that are supported by the Prosit models, which is why there is no additional configuration for this. The only other modificaitons is TMT if you specify the tag in the config and use a TMT-Prosit model. This is because of how Prosit models were trained. N-term acetylated peptides are overall not so common, which led to the decision not to support it back in the days, as the number of identified proteins didn't increase because of that. 
Right now, if you have peptides with n-actylation or any other modification, they are filtered out. You should see the number of filtered peptides in the log file, where it reads "Number of peptides before / after filtering".
We will start to support other models, such as AlphaPept, DeepLC, and MS2PIP starting with the next release (0.7.0) which may support additional modifications, and will add the possibility to customize the modifications in the config accordingly. In addition, the new Prosit-PTM model is worked on, which is theoretically supporting any modification one could think of.

**Comment by ZhaoYaniBruker** [comment] 2024-07-16 11:49
Dear Picciama,

Congratulations on the new release :D. I will try it out soon.

1) Actually, I find another problem when I analyze the generated spectral library from the old version. I have set the peptide length ranges from 7 to 50, but I only got peptides with lengths up to 30. Please find the attached config. I wonder if this is due to the collisionEnergy setting, or it is a bug?
2) I am also interested in the rescoring, and I don't have much knowledge about it. It looks like the Oktoberfest rescore can only work on DDA data (am I right?), are there any software tools or any ways to rescore DIA data too?

With best regards.

**Comment by picciama** [comment] 2024-07-16 12:46
Release is unfortunately not yet fully ready, I have released new versions of the dependency packages and try to test this now. before officially releasing it. Regarding your questions:
1. Depending on the prediction model you choose, there are limitations wrt. to the peptides that are supported. This is due to limitations that arise from the model architecture. Prosit for instance, was designed to capture as many peptides as possible while maintaining fast inference and limiting its complexity. This is why it was designed to support peptides with a length of 7-30 aas, as most peptides we see fall into this range. This is why Oktoberfest filters out longer (and shorter) peptides.

**Comment by ZhaoYaniBruker** [comment] 2024-07-16 13:19
Dear Mario,

I am very grateful for your quick and nice reply and comments. 

Thanks for pointing out the peptide length limits, that is really useful for benchmarking.

Thanks for your answer, I now understand more about rescoring. However, again like in Oktoberfest spectral library generator, I am a bit confused about the default modifications taking into account in Oktoberfest rescoring. I have read your Nature paper: it is written that carbamidomethylation as fixed modification, and N-terminal acetylation and methionine oxidation as variable modifications. Yet, it is said that Carbamidomethylated cysteine was not included as a fixed modification for the comparison dataset. 
So my question would be: what would be the default modifications in rescoring? none?

With best regards.

**Comment by picciama** [comment] 2024-07-16 14:46
Regarding variable n-acetylation and unmodified cystein: We never trained models with this, because ProteomeTools, from where the synthetic peptide came that we needed to train the models do not contain such peptides. Therefore, Oktoberfest automatically assumes that cysteins are carbamidmethylated and filters out n-acetlyated peptides.

In the timsTOF paper, we used data from Fossati et al. and merely described how they were searching it. So also here, n-acetylated peptides were filtered out in oktoberfest. For comparison of Orbitrap versus timsTOF rescoring, we needed a datasets that measured HLA peptides on both instruments, so we chose the Gravel et al. dataset. Because they were not performing carbamidomethlation, we filtered out peptides containing cystein prior to rescoring. 

Therefore, Oktoberfest always assumes C-carb as a fixed and M-ox as a variable modification and also doesn't support anything else, except TMT mods for the TMT-capable models. However, the new Prosit-PTM model will change that, and so Oktoberfest will also support additional modifications, which can then be specified in the configuration by the user.

**Comment by picciama** [comment] 2024-07-16 14:54
> Thanks for your answer, I now understand more about rescoring. Regarding to the modifications in rescoring, I think I understand now: it depends on the parameters one sets while using MaxQuant :D.

Be careful, the modifications do not depend on what you set in MQ. You can obviously search with many modifications in MQ, but the limiting factor are the prediction models that are available. So Oktoberfest will always filter out everything that is not supported by the model!

**Comment by ZhaoYaniBruker** [comment] 2024-07-17 17:54
I have tested oktoberfest rescoring on MQ, works perfect. When I move to Sage, it however gives some errors. The config is:
![Screenshot 2024-07-17 195037](https://github.com/user-attachments/assets/84dc0701-229b-4dcc-8391-d94e41059f42)

The error is:
![Screenshot 2024-07-17 195055](https://github.com/user-attachments/assets/77e302fe-e97e-4dfe-8b4a-a43d4ec6e0f3)

What would be the cause here? I am looking forward to seeing your answer.

**Comment by picciama** [comment] 2024-07-17 20:25
Oktoberfest only supports MQ when rescoring timsTOF data. The challenge is how raw spectra are aggregated to MS2 by the search engine and how the search engine hits can be mapped back to the raw spectra in the d folder, to aggregate them as well to get the MS2 level intensities. 
We implemented this for MQ, and support for MSFragger is planned. For Sage, we never tested this and I would need to talk to lazaer (Sage maintainer) to see how we can do this.

Oktoberfest should actually stop and tell you that you can only use spectra_type="d" in combination with search_engine="maxquant", but I will need to check again to see why it didn't do that in your case.

I also have the suspicion, that sth. in the Sage output may have changed between versions, which may lead to the first error message you receive.
Could you please tell me which version of Sage you were using and ideally also send me the first two rows (header + 1 PSM row)?

The second error most likely arises from the fact that our mzml parser was never intended to be used with timsTOF data. We rely on converting .d to hdf using alphatims, as it allows to read only specific raw spectra for which we actually have hits by the search engine, thus avoiding huge memory explosions when dealing with large datasets, once the d folder was converted to hdf at least once.
I don't know how best to support mzml for timsTOF case, because I am not sure exactly how MS2 level spectra would be stored and never looked into it. 
I also don't know if mzml is generally the preferred way over supplying the d folder or an already converted hdf file.

**Comment by ZhaoYaniBruker** [comment] 2024-07-18 07:18
Dera Mario,

I have Sage version 0.14.4.

Few lines of Sage output are attached here:
peptide proteins        num_proteins    filename        scannr  rank    label   expmass calcmass        charge  peptide_len     missed_cleavages        isotope_error   precursor_ppm   fragment_ppm     hyperscore      delta_next      delta_best      rt      aligned_rt      predicted_rt    delta_rt_model  matched_peaks   longest_b       longest_y       longest_y_pct   matched_intensity_pct    scored_candidates       poisson sage_discriminant_score posterior_error spectrum_q      peptide_q       protein_q       ms1_intensity   ms2_intensity
VVLLGEFLHPC[+57.0216]EDDIVC[+57.0216]K  sp|Q9NY12|GAR1_HUMAN    1       B_20230927_IO15x75_HeLa_400ng_15min_PASEF_06to15_Slot2-8_1_6487.d       60746   1       1       2142.0562       2142.049 3       18      0       0.0     3.3052773       8.457472        37.94702352526845       37.94702352526845       0.0     15.076681       0.75383407      0.7563776       0.002543509      13      1       7       0.3888889       37.331467       384     -9.939175662369385      0.9891276       -63.95509       0.000057257374  0.000098721976  0.00031930223   59147.0 74732.0
EAIDSPVSFLALHNQIR       sp|Q92900|RENT1_HUMAN   1       B_20230927_IO15x75_HeLa_400ng_15min_PASEF_06to15_Slot2-8_1_6487.d       54418   1       1       1909.02 1909.0059       3       17       0       0.0     7.4175277       4.5374055       29.008742489531706      29.008742489531706      0.0     14.105062       0.70525306      0.7025821       0.0026709437    11      07       0.4117647       16.584265       433     -7.907185630908808      0.9714641       -56.83898       0.000057257374  0.000098721976  0.00031930223   16553.0 11103.0
(base) yani@r2d2:~/public_sage$ head -5 results.sage.tsv
peptide proteins        num_proteins    filename        scannr  rank    label   expmass calcmass        charge  peptide_len     missed_cleavages        isotope_error   precursor_ppm   fragment_ppm     hyperscore      delta_next      delta_best      rt      aligned_rt      predicted_rt    delta_rt_model  matched_peaks   longest_b       longest_y       longest_y_pct   matched_intensity_pct    scored_candidates       poisson sage_discriminant_score posterior_error spectrum_q      peptide_q       protein_q       ms1_intensity   ms2_intensity
VVLLGEFLHPC[+57.0216]EDDIVC[+57.0216]K  sp|Q9NY12|GAR1_HUMAN    1       B_20230927_IO15x75_HeLa_400ng_15min_PASEF_06to15_Slot2-8_1_6487.d       60746   1       1       2142.0562       2142.049 3       18      0       0.0     3.3052773       8.457472        37.94702352526845       37.94702352526845       0.0     15.076681       0.75383407      0.7563776       0.002543509      13      1       7       0.3888889       37.331467       384     -9.939175662369385      0.9891276       -63.95509       0.000057257374  0.000098721976  0.00031930223   59147.0 74732.0
EAIDSPVSFLALHNQIR       sp|Q92900|RENT1_HUMAN   1       B_20230927_IO15x75_HeLa_400ng_15min_PASEF_06to15_Slot2-8_1_6487.d       54418   1       1       1909.02 1909.0059       3       17       0       0.0     7.4175277       4.5374055       29.008742489531706      29.008742489531706      0.0     14.105062       0.70525306      0.7025821       0.0026709437    11      07       0.4117647       16.584265       433     -7.907185630908808      0.9714641       -56.83898       0.000057257374  0.000098721976  0.00031930223   16553.0 11103.0
MEEDPDDVPHGHITSLAVK     sp|P41227|NAA10_HUMAN   1       B_20230927_IO15x75_HeLa_400ng_15min_PASEF_06to15_Slot2-8_1_6487.d       25936   1       1       2088.989        2088.9785       319      0       0.0     5.025432        7.1123247       32.84235456319327       32.84235456319327       0.0     9.396451        0.46982256      0.47488138      0.005058825     11      17       0.36842105      17.35257        206     -8.171445349046774      0.96620446      -54.80788       0.000057257374  0.000098721976  0.00031930223   37912.0 21542.0
YALQMEQLNGILLHLESELAQTR sp|P05783|K1C18_HUMAN   1       B_20230927_IO15x75_HeLa_400ng_15min_PASEF_06to15_Slot2-8_1_6487.d       75832   1       1       2669.3982       2669.3848       323      0       0.0     5.03026 6.7081027       37.011977401525314      22.424393154556977      0.0     17.393608       0.8696804       0.88561666      0.015936255     13      1       70.3043478       20.705421       176     -10.277421757230503     0.95839936      -51.88696       0.000057257374  0.000098721976  0.00031930223   121570.0        34600.0

**Comment by picciama** [comment] 2024-07-18 08:47
Indeed, sth. I have missed. I implemented a fix for this which will appear in the next spectrum_io patch release, which oktoberfest will make use of then.

**Comment by picciama** [comment] 2024-07-18 11:12
This is valueable information! We are currently relying on matching the peaks of the raw spectra to the theoretical monoisotopic masses of each fragment, so this could make the spectra annotation much faster, at least for Sage! I will add it to my feature list.

**Closed** 2024-07-18 11:50 UTC
Labels: question
